when:
  - branch: main
    event: push
  - event: pull_request

steps:
  test:
    image: golang:${GO_VERSION}
    commands:
      - go test -race -coverprofile coverage_${GO_VERSION}.out ./...

matrix:
  GO_VERSION:
    - 1.13
    - 1.16
    - 1.18
    - 1.20
